class chat {
    constructor(TenantId, From, To, FromMe, LastMessage, IsRead, TimeStamp, UnreadCount) {
      this.TenantId = TenantId; // represents the id generated by the firestore
      this.From = From;
      this.To = To; 
      this.FromMe = FromMe; 
      this.LastMessage = LastMessage; 
      this.TimeStamp = TimeStamp;
      this.UnreadCount = UnreadCount;
    }
  }
   
  module.exports = chat;